language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
  - yarn install
script:
  - cargo clippy
  - cargo test
  - yarn eslint js/*